### PR TITLE
Removed legacy icons definition.

### PR DESCRIPTION
**Pull request by ivarconr**
It uses icons already deleted in commit 26dda8cb8c75.

Fixes build when using spaden with webpack.

### CODE REVIEW

**Comment by ivarconr** [comment]
either merge or close this issue..

**Comment by sveisvei** [comment]
+1 for cleanup and merge. @Skadefryd

**Comment by ivarconr** [comment]
Yes, it would probably require sone cleanup now.

**Comment by Skadefryd** [comment]
Cleaned as part of Spaden v.5.0.0

**Pull request closed without merging**
